// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cS9ny1PQVvl4qt0Wtb8Z9C42aoXbSgk',
    appId: '1:593605657417:web:59e9cf3f255d29f2aed098',
    messagingSenderId: '593605657417',
    projectId: 'aljauharapp',
    authDomain: 'aljauharapp.firebaseapp.com',
    storageBucket: 'aljauharapp.firebasestorage.app',
    measurementId: 'G-RJGFZCCBGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMCCe0mDjWBQ0NXI1zmxxuOQuIlS905A',
    appId: '1:593605657417:android:a253509e8a8bfc10aed098',
    messagingSenderId: '593605657417',
    projectId: 'aljauharapp',
    storageBucket: 'aljauharapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDToQojQOcsO_pcU0pgs40pkdls3xO8I',
    appId: '1:593605657417:ios:886baec34bb19ba9aed098',
    messagingSenderId: '593605657417',
    projectId: 'aljauharapp',
    storageBucket: 'aljauharapp.firebasestorage.app',
    iosBundleId: 'com.app.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDToQojQOcsO_pcU0pgs40pkdls3xO8I',
    appId: '1:593605657417:ios:886baec34bb19ba9aed098',
    messagingSenderId: '593605657417',
    projectId: 'aljauharapp',
    storageBucket: 'aljauharapp.firebasestorage.app',
    iosBundleId: 'com.app.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuE5wQrMyboMVhSO8g0EYOdiJ0EyZ79lc',
    appId: '1:593605657417:web:e508a36b8d019f42aed098',
    messagingSenderId: '593605657417',
    projectId: 'aljauharapp',
    authDomain: 'aljauharapp.firebaseapp.com',
    storageBucket: 'aljauharapp.firebasestorage.app',
    measurementId: 'G-ESQPEHGWMT',
  );
}
